=== ipad54/INether/resources/nbt_upgrade_schema_schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$defs": {
		"blockStateProperty": {
			"type": "object",
			"minProperties": 1,
			"maxProperties": 1,
			"additionalProperties": false,
			"properties": {
				"int": {
					"type": "integer"
				},
				"string": {
					"type": "string"
				},
				"byte": {
					"type": "integer"
				}
			}
		}
	},
	"type": "object",
	"additionalProperties": false,
	"required": [
		"maxVersionMajor",
		"maxVersionMinor",
		"maxVersionPatch",
		"maxVersionRevision"
	],
	"properties": {
		"maxVersionMajor": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionMinor": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionPatch": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionRevision": {
			"type": "integer",
			"minimum": 0
		},
		"renamedIds": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"renamedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			}
		},
		"addedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"$ref": "#/$defs/blockStateProperty"
				}
			}
		},
		"removedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "string"
				}
			}
		},
		"remappedPropertyValues": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			}
		},
		"remappedPropertyValuesIndex": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "object",
					"properties": {
						"old": {
							"$ref": "#/$defs/blockStateProperty"
						},
						"new": {
							"$ref": "#/$defs/blockStateProperty"
						}
					}
				}
			}
		},
		"remappedStates": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "object",
					"properties": {
						"oldState": {
							"type": ["object", "null"],
							"additionalProperties": {
								"$ref": "#/$defs/blockStateProperty"
							}
						},
						"newId": {
							"type": "string"
						},
						"newState": {
							"type": ["object", "null"],
							"additionalProperties": {
								"$ref": "#/$defs/blockStateProperty"
							}
						}
					}
				}
			}
		}
	}
}

=== ipad54/INether/resources/Beans/0041_1.14.0_to_1.16.0.57_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 16,
    "maxVersionPatch": 0,
    "maxVersionRevision": 0,
    "addedProperties": {
        "minecraft:cobblestone_wall": {
            "wall_connection_type_east": {
                "string": "none"
            },
            "wall_connection_type_north": {
                "string": "none"
            },
            "wall_connection_type_south": {
                "string": "none"
            },
            "wall_connection_type_west": {
                "string": "none"
            },
            "wall_post_bit": {
                "byte": 0
            }
        },
        "minecraft:jigsaw": {
            "rotation": {
                "int": 0
            }
        }
    }
}

=== ipad54/INether/resources/nbt_upgrade_schema/0011_1.10.0_to_1.12.0.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 12,
    "maxVersionPatch": 0,
    "maxVersionRevision": 1,
    "addedProperties": {
        "minecraft:barrel": {
            "open_bit": {
                "byte": 0
            }
        },
        "minecraft:bell": {
            "toggle_bit": {
                "byte": 0
            }
        },
        "minecraft:campfire": {
            "direction": {
                "int": 0
            },
            "extinguished": {
                "byte": 0
            }
        },
        "minecraft:lectern": {
            "powered_bit": {
                "byte": 0
            }
        }
    },
    "renamedProperties": {
        "minecraft:blast_furnace": {
            "direction": "facing_direction"
        },
        "minecraft:composter": {
            "fill_level": "composter_fill_level"
        },
        "minecraft:coral_fan": {
            "direction": "coral_fan_direction"
        },
        "minecraft:coral_fan_dead": {
            "direction": "coral_fan_direction"
        },
        "minecraft:smoker": {
            "direction": "facing_direction"
        }
    },
    "remappedPropertyValues": {
        "minecraft:barrel": {
            "facing_direction": "facing_direction_00"
        },
        "minecraft:blast_furnace": {
            "direction": "direction_01"
        },
        "minecraft:smoker": {
            "direction": "direction_01"
        }
    },
    "remappedPropertyValuesIndex": {
        "facing_direction_00": [
            {
                "old": {
                    "int": 7
                },
                "new": {
                    "int": 0
                }
            },
            {
                "old": {
                    "int": 6
                },
                "new": {
                    "int": 0
                }
            }
        ],
        "direction_01": [
            {
                "old": {
                    "int": 0
                },
                "new": {
                    "int": 3
                }
            },
            {
                "old": {
                    "int": 1
                },
                "new": {
                    "int": 4
                }
            },
            {
                "old": {
                    "int": 3
                },
                "new": {
                    "int": 5
                }
            }
        ]
    }
}

=== ipad54/INether/resources/nbt_upgrade_schema/0071_1.16.0_to_1.16.100.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 16,
    "maxVersionPatch": 0,
    "maxVersionRevision": 16,
    "addedProperties": {
        "minecraft:chain": {
            "pillar_axis": {
                "string": "y"
            }
        }
    },
    "renamedProperties": {
        "minecraft:bee_nest": {
            "facing_direction": "direction"
        },
        "minecraft:beehive": {
            "facing_direction": "direction"
        }
    },
    "remappedPropertyValues": {
        "minecraft:bee_nest": {
            "facing_direction": "facing_direction_00"
        },
        "minecraft:beehive": {
            "facing_direction": "facing_direction_00"
        }
    },
    "remappedPropertyValuesIndex": {
        "facing_direction_00": [
            {
                "old": {
                    "int": 4
                },
                "new": {
                    "int": 1
                }
            },
            {
                "old": {
                    "int": 3
                },
                "new": {
                    "int": 0
                }
            },
            {
                "old": {
                    "int": 5
                },
                "new": {
                    "int": 3
                }
            },
            {
                "old": {
                    "int": 1
                },
                "new": {
                    "int": 0
                }
            }
        ]
    }
}
