=== ipad54/INether/resources/nbt_upgrade_schema_schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$defs": {
		"blockStateProperty": {
			"type": "object",
			"minProperties": 1,
			"maxProperties": 1,
			"additionalProperties": false,
			"properties": {
				"int": {
					"type": "integer"
				},
				"string": {
					"type": "string"
				},
				"byte": {
					"type": "integer"
				}
			}
		}
	},
	"type": "object",
	"additionalProperties": false,
	"required": [
		"maxVersionMajor",
		"maxVersionMinor",
		"maxVersionPatch",
		"maxVersionRevision"
	],
	"properties": {
		"maxVersionMajor": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionMinor": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionPatch": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionRevision": {
			"type": "integer",
			"minimum": 0
		},
		"renamedIds": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"renamedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			}
		},
		"addedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"$ref": "#/$defs/blockStateProperty"
				}
			}
		},
		"removedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "string"
				}
			}
		},
		"remappedPropertyValues": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			}
		},
		"remappedPropertyValuesIndex": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "object",
					"properties": {
						"old": {
							"$ref": "#/$defs/blockStateProperty"
						},
						"new": {
							"$ref": "#/$defs/blockStateProperty"
						}
					}
				}
			}
		},
		"remappedStates": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "object",
					"properties": {
						"oldState": {
							"type": ["object", "null"],
							"additionalProperties": {
								"$ref": "#/$defs/blockStateProperty"
							}
						},
						"newId": {
							"type": "string"
						},
						"newState": {
							"type": ["object", "null"],
							"additionalProperties": {
								"$ref": "#/$defs/blockStateProperty"
							}
						}
					}
				}
			}
		}
	}
}

=== ipad54/INether/resources/Beans/0121_1.18.10_to_1.18.20.27_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 18,
    "maxVersionPatch": 10,
    "maxVersionRevision": 1,
    "addedProperties": {
        "minecraft:ochre_froglight": {
            "pillar_axis": {
                "string": "y"
            }
        },
        "minecraft:pearlescent_froglight": {
            "pillar_axis": {
                "string": "y"
            }
        },
        "minecraft:verdant_froglight": {
            "pillar_axis": {
                "string": "y"
            }
        }
    },
    "renamedIds": {
        "minecraft:frog_egg": "minecraft:frog_spawn"
    }
}

=== ipad54/INether/resources/nbt_upgrade_schema/0111_1.18.0_to_1.18.10.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 18,
    "maxVersionPatch": 10,
    "maxVersionRevision": 1,
    "removedProperties": {
        "minecraft:skull": [
            "no_drop_bit"
        ]
    },
    "remappedPropertyValues": {
        "minecraft:glow_lichen": {
            "multi_face_direction_bits": "multi_face_direction_bits_00"
        },
        "minecraft:sculk_vein": {
            "multi_face_direction_bits": "multi_face_direction_bits_00"
        }
    },
    "remappedPropertyValuesIndex": {
        "multi_face_direction_bits_00": [
            {
                "old": {
                    "int": 4
                },
                "new": {
                    "int": 16
                }
            },
            {
                "old": {
                    "int": 5
                },
                "new": {
                    "int": 17
                }
            },
            {
                "old": {
                    "int": 6
                },
                "new": {
                    "int": 18
                }
            },
            {
                "old": {
                    "int": 7
                },
                "new": {
                    "int": 19
                }
            },
            {
                "old": {
                    "int": 8
                },
                "new": {
                    "int": 4
                }
            },
            {
                "old": {
                    "int": 9
                },
                "new": {
                    "int": 5
                }
            },
            {
                "old": {
                    "int": 10
                },
                "new": {
                    "int": 6
                }
            },
            {
                "old": {
                    "int": 11
                },
                "new": {
                    "int": 7
                }
            },
            {
                "old": {
                    "int": 12
                },
                "new": {
                    "int": 20
                }
            },
            {
                "old": {
                    "int": 13
                },
                "new": {
                    "int": 21
                }
            },
            {
                "old": {
                    "int": 14
                },
                "new": {
                    "int": 22
                }
            },
            {
                "old": {
                    "int": 15
                },
                "new": {
                    "int": 23
                }
            },
            {
                "old": {
                    "int": 16
                },
                "new": {
                    "int": 8
                }
            },
            {
                "old": {
                    "int": 17
                },
                "new": {
                    "int": 9
                }
            },
            {
                "old": {
                    "int": 18
                },
                "new": {
                    "int": 10
                }
            },
            {
                "old": {
                    "int": 19
                },
                "new": {
                    "int": 11
                }
            },
            {
                "old": {
                    "int": 20
                },
                "new": {
                    "int": 24
                }
            },
            {
                "old": {
                    "int": 21
                },
                "new": {
                    "int": 25
                }
            },
            {
                "old": {
                    "int": 22
                },
                "new": {
                    "int": 26
                }
            },
            {
                "old": {
                    "int": 23
                },
                "new": {
                    "int": 27
                }
            },
            {
                "old": {
                    "int": 24
                },
                "new": {
                    "int": 12
                }
            },
            {
                "old": {
                    "int": 25
                },
                "new": {
                    "int": 13
                }
            },
            {
                "old": {
                    "int": 26
                },
                "new": {
                    "int": 14
                }
            },
            {
                "old": {
                    "int": 27
                },
                "new": {
                    "int": 15
                }
            },
            {
                "old": {
                    "int": 36
                },
                "new": {
                    "int": 48
                }
            },
            {
                "old": {
                    "int": 37
                },
                "new": {
                    "int": 49
                }
            },
            {
                "old": {
                    "int": 38
                },
                "new": {
                    "int": 50
                }
            },
            {
                "old": {
                    "int": 39
                },
                "new": {
                    "int": 51
                }
            },
            {
                "old": {
                    "int": 40
                },
                "new": {
                    "int": 36
                }
            },
            {
                "old": {
                    "int": 41
                },
                "new": {
                    "int": 37
                }
            },
            {
                "old": {
                    "int": 42
                },
                "new": {
                    "int": 38
                }
            },
            {
                "old": {
                    "int": 43
                },
                "new": {
                    "int": 39
                }
            },
            {
                "old": {
                    "int": 44
                },
                "new": {
                    "int": 52
                }
            },
            {
                "old": {
                    "int": 45
                },
                "new": {
                    "int": 53
                }
            },
            {
                "old": {
                    "int": 46
                },
                "new": {
                    "int": 54
                }
            },
            {
                "old": {
                    "int": 47
                },
                "new": {
                    "int": 55
                }
            },
            {
                "old": {
                    "int": 48
                },
                "new": {
                    "int": 40
                }
            },
            {
                "old": {
                    "int": 49
                },
                "new": {
                    "int": 41
                }
            },
            {
                "old": {
                    "int": 50
                },
                "new": {
                    "int": 42
                }
            },
            {
                "old": {
                    "int": 51
                },
                "new": {
                    "int": 43
                }
            },
            {
                "old": {
                    "int": 52
                },
                "new": {
                    "int": 56
                }
            },
            {
                "old": {
                    "int": 53
                },
                "new": {
                    "int": 57
                }
            },
            {
                "old": {
                    "int": 54
                },
                "new": {
                    "int": 58
                }
            },
            {
                "old": {
                    "int": 55
                },
                "new": {
                    "int": 59
                }
            },
            {
                "old": {
                    "int": 56
                },
                "new": {
                    "int": 44
                }
            },
            {
                "old": {
                    "int": 57
                },
                "new": {
                    "int": 45
                }
            },
            {
                "old": {
                    "int": 58
                },
                "new": {
                    "int": 46
                }
            },
            {
                "old": {
                    "int": 59
                },
                "new": {
                    "int": 47
                }
            }
        ]
    }
}

=== ipad54/INether/resources/nbt_upgrade_schema/0091_1.17.10_to_1.17.30.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 16,
    "maxVersionPatch": 210,
    "maxVersionRevision": 3,
    "addedProperties": {
        "minecraft:frame": {
            "item_frame_photo_bit": {
                "byte": 0
            }
        },
        "minecraft:glow_frame": {
            "item_frame_photo_bit": {
                "byte": 0
            }
        }
    }
}

=== ipad54/INether/resources/nbt_upgrade_schema/0171_1.19.60_to_1.19.70.26_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 19,
    "maxVersionPatch": 70,
    "maxVersionRevision": 15,
    "remappedStates": {
        "minecraft:wool": [
            {
                "oldState": {
                    "color": {
                        "string": "white"
                    }
                },
                "newName": "minecraft:white_wool",
                "newState": null
            },
            {
                "oldState": {
                    "color": {
                        "string": "orange"
                    }
                },
                "newName": "minecraft:orange_wool",
                "newState": null
            },
            {
                "oldState": {
                    "color": {
                        "string": "magenta"
                    }
                },
                "newName": "minecraft:magenta_wool",
                "newState": null
            },
            {
                "oldState": {
                    "color": {
                        "string": "light_blue"
                    }
                },
                "newName": "minecraft:light_blue_wool",
                "newState": null
            },
            {
                "oldState": {
                    "color": {
                        "string": "yellow"
                    }
                },
                "newName": "minecraft:yellow_wool",
                "newState": null
            },
            {
                "oldState": {
                    "color": {
                        "string": "lime"
                    }
                },
                "newName": "minecraft:lime_wool",
                "newState": null
            },
            {
                "oldState": {
                    "color": {
                        "string": "pink"
                    }
                },
                "newName": "minecraft:pink_wool",
                "newState": null
            },
            {
                "oldState": {
                    "color": {
                        "string": "gray"
                    }
                },
                "newName": "minecraft:gray_wool",
                "newState": null
            },
            {
                "oldState": {
                    "color": {
                        "string": "silver"
                    }
                },
                "newName": "minecraft:light_gray_wool",
                "newState": null
            },
            {
                "oldState": {
                    "color": {
                        "string": "cyan"
                    }
                },
                "newName": "minecraft:cyan_wool",
                "newState": null
            },
            {
                "oldState": {
                    "color": {
                        "string": "purple"
                    }
                },
                "newName": "minecraft:purple_wool",
                "newState": null
            },
            {
                "oldState": {
                    "color": {
                        "string": "blue"
                    }
                },
                "newName": "minecraft:blue_wool",
                "newState": null
            },
            {
                "oldState": {
                    "color": {
                        "string": "brown"
                    }
                },
                "newName": "minecraft:brown_wool",
                "newState": null
            },
            {
                "oldState": {
                    "color": {
                        "string": "green"
                    }
                },
                "newName": "minecraft:green_wool",
                "newState": null
            },
            {
                "oldState": {
                    "color": {
                        "string": "red"
                    }
                },
                "newName": "minecraft:red_wool",
                "newState": null
            },
            {
                "oldState": {
                    "color": {
                        "string": "black"
                    }
                },
                "newName": "minecraft:black_wool",
                "newState": null
            }
        ]
    }
}

=== ipad54/INether/resources/Beans/0131_1.18.20.27_beta_to_1.18.30.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 18,
    "maxVersionPatch": 10,
    "maxVersionRevision": 1,
    "renamedIds": {
        "minecraft:concretePowder": "minecraft:concrete_powder",
        "minecraft:invisibleBedrock": "minecraft:invisible_bedrock",
        "minecraft:movingBlock": "minecraft:moving_block",
        "minecraft:mysterious_frame": "minecraft:reinforced_deepslate",
        "minecraft:mysterious_frame_slot": "minecraft:reinforced_deepslate",
        "minecraft:pistonArmCollision": "minecraft:piston_arm_collision",
        "minecraft:seaLantern": "minecraft:sea_lantern",
        "minecraft:stickyPistonArmCollision": "minecraft:sticky_piston_arm_collision",
        "minecraft:tripWire": "minecraft:trip_wire"
    }
}

=== ipad54/INether/resources/Beans/0051_1.16.0.57_beta_to_1.16.0.59_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 16,
    "maxVersionPatch": 0,
    "maxVersionRevision": 9,
    "renamedIds": {
        "minecraft:basalt_block": "minecraft:basalt",
        "minecraft:blue_fire": "minecraft:soul_fire",
        "minecraft:blue_nether_wart_block": "minecraft:warped_wart_block",
        "minecraft:crimson_trap_door": "minecraft:crimson_trapdoor",
        "minecraft:polished_basalt_block": "minecraft:polished_basalt",
        "minecraft:shroomlight_block": "minecraft:shroomlight",
        "minecraft:soul_soil_block": "minecraft:soul_soil",
        "minecraft:target_block": "minecraft:target",
        "minecraft:weeping_vines_block": "minecraft:weeping_vines"
    }
}

=== ipad54/INether/resources/nbt_upgrade_schema/0081_1.16.200_to_1.16.210.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 16,
    "maxVersionPatch": 210,
    "maxVersionRevision": 3,
    "removedProperties": {
        "minecraft:stripped_crimson_hyphae": [
            "deprecated"
        ],
        "minecraft:stripped_crimson_stem": [
            "deprecated"
        ],
        "minecraft:stripped_warped_hyphae": [
            "deprecated"
        ],
        "minecraft:stripped_warped_stem": [
            "deprecated"
        ]
    }
}

=== ipad54/INether/resources/Beans/0061_1.16.0.59_beta_to_1.16.0.68_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 16,
    "maxVersionPatch": 0,
    "maxVersionRevision": 14,
    "renamedIds": {
        "minecraft:lodestone_block": "minecraft:lodestone",
        "minecraft:twisting_vines_block": "minecraft:twisting_vines"
    },
    "addedProperties": {
        "minecraft:melon_stem": {
            "facing_direction": {
                "int": 0
            }
        },
        "minecraft:pumpkin_stem": {
            "facing_direction": {
                "int": 0
            }
        }
    },
    "removedProperties": {
        "minecraft:blackstone_wall": [
            "wall_block_type"
        ],
        "minecraft:polished_blackstone_brick_wall": [
            "wall_block_type"
        ],
        "minecraft:polished_blackstone_wall": [
            "wall_block_type"
        ]
    },
    "remappedPropertyValues": {
        "minecraft:cobblestone_wall": {
            "wall_block_type": "wall_block_type_00"
        }
    },
    "remappedPropertyValuesIndex": {
        "wall_block_type_00": [
            {
                "old": {
                    "string": "blackstone"
                },
                "new": {
                    "string": "cobblestone"
                }
            },
            {
                "old": {
                    "string": "polished_blackstone_brick"
                },
                "new": {
                    "string": "cobblestone"
                }
            },
            {
                "old": {
                    "string": "polished_blackstone"
                },
                "new": {
                    "string": "cobblestone"
                }
            }
        ]
    }
}
